-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Users Table
create table tg_users (
  id bigint generated by default as identity primary key,
  user_uuid uuid default uuid_generate_v4() not null unique,
  first_name text,
  last_name text,
  username text,
  is_blocked boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Messages Table
create table tg_messages (
  id bigint generated by default as identity primary key,
  user_id bigint references tg_users(id) on delete cascade not null,
  direction text check (direction in ('user_to_admin', 'admin_to_user')) not null,
  text text not null,
  is_read boolean default false,
  sent_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Admins Table (Optional, for future use)
create table tg_admins (
  id bigint generated by default as identity primary key,
  chat_id bigint not null unique,
  name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes for performance
create index idx_tg_messages_user_id on tg_messages(user_id);
create index idx_tg_users_user_uuid on tg_users(user_uuid);

-- RLS Policies (Open for now, but good practice to enable)
alter table tg_users enable row level security;
alter table tg_messages enable row level security;

create policy "Public users can insert" on tg_users for insert with check (true);
create policy "Public users can select" on tg_users for select using (true);

create policy "Public messages insert" on tg_messages for insert with check (true);
create policy "Public messages select" on tg_messages for select using (true);
